/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package painter.app;

import isel.mpd.painter0.utils.RandomUtils;
import org.junit.jupiter.api.Test;

import java.awt.*;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class MessageUtilsTest {
    @Test void testGetMessage() {

    }

    @Test
    void testGetRandomInt() {
        RandomUtils random = new RandomUtils();
        try {
            random.getRandomInt(3, 2);
        } catch (IllegalArgumentException e) {
            return;
        }
        fail();
    }

    @Test
    void testGetRandomPoint() {
        int sizeX = 500;
        int sizeY = 500;

        Point p = RandomUtils.getRandomPoint(sizeX, sizeY);
        assertTrue(p.x < 500);
        assertTrue(p.y < 500);
    }
}
